#!/usr/bin/env bash
#Getting details of a subdomain

dom_info () {
    #performs a DNS lookup for a specific subdomain
    line=$(dig "$2"."$1" | grep -A1 'ANSWER SECTION:' | tr '\t' '\n' | tail -2 | tr '\n' ' ')
    echo "$2 $line" | awk '{print "The subdomain " $1 " is a " $2 " record and points to " $3 }'
}
if [ $# -eq 1 ]; then
    #When only one argument is provided
    dom_info "$1" "www"
    dom_info "$1" "lb-01"
    dom_info "$1" "web-01"
    dom_info "$1" "web-02"
elif [ "$#" -eq 2 ]; then
    dom_info "$1" "$2"
fi
