#!/usr/bin/env bash
#Debugs issues with nginx not running on port 80
rm /etc/nginx/sites-enabled/default
ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
service nginx  restart
