#!/usr/bin/env bash
# Displays numbers frnom 1 to 20
count=1
while [ $count -le 20 ]; do
	echo "$count"
	if [ $count == 4 ]; then
		echo "bad uck from china"
	elif [ $count == 9 ]; then
		echo "bad luck from Japan"
	elif [ $count == 17 ]; then
		echo "bad luck from Italy"
	fi
	((count++))

done

