#!/usr/bin/env bash
#debugging nginx and running it as user nginx

#changing user to nginx
sed -i "s/#user www-data/user nginx/" /etc/nginx/nginx.conf
#adding port 8080
sed -i "s/80/8080/g" /etc/nginx/sites-available/default

chmod 644 /etc/nginx/nginx.conf
#stopping the apache process
pkill apache2

#starting nginx
sudo -u nginx service nginx start
